name: Test Cookie
description: Use cookie cutter and test pre-commit
inputs:
  backend:
    description: Backend to run
    required: true

runs:
  using: composite
  steps:
    - name: "${{ inputs.backend }}: Run cookiecutter"
      shell: bash
      run: cookiecutter --no-input . --config-file tests/${{ inputs.backend }}.yml

    - name: "${{ inputs.backend }}: Replace with ookiecutter"
      shell: bash
      run: |
        rm -r README.md cookiecutter.json hooks tests \{\{cookiecutter.project_name\}\} .github
        mv cookie-${{ inputs.backend }}/* .
        mv cookie-${{ inputs.backend }}/.??* .
        git add .

    - name: "${{ inputs.backend }}: Run pre-commit"
      shell: bash
      run: pre-commit run --all-files --hook-stage manual --show-diff-on-failure

    - name: "${{ inputs.backend }}: Reset"
      shell: bash
      run: |
        git reset --hard
        git clean -fxd

